export const ROUTES = {
    HOME: '/',
    BUNDLES: '/legajos',
    CREATE_BUNDLE:'/legajos/crear',
    UPDATE_BUNDLE:'/legajos/actualizar/:id',
    SALARY:'/sueldos',
    SALARY_DETAIL:'/sueldos/detalle/:id',
    CONCEPTS:'/conceptos',
    CREATE_CONCEPT:'/conceptos/crear',
    UPDATE_CONCEPT:'/conceptos/actualizar/:id',
    SETTLEMENT_PERIOD:'/periodos',
    CREATE_SETTLEMENT_PERIOD:'/periodos/crear',
    UPDATE_SETTLEMENT_PERIOD:'/periodos/actualizar/:id',
    NOVELTY:'/novedades',
    CREATE_NOVELTY:'/novedades/crear',
    DETAIL_NOVELTY:'/novedades/detalle/:id',
    LOGIN: '/login',
};